/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.easyfixing.mainFunctionalities.AdminUpdateDatabase;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author hieut
 */
public class AdminUpdateWorkerService extends javax.swing.JFrame {

    /**
     * Creates new form AdminDeleteWorker
     */
    public AdminUpdateWorkerService() {
        // init workers' current services List
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        searchWorkerLabel = new javax.swing.JLabel();
        nameBtn = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        //String province[] = {"Ha Noi", "Vinh Phuc"};
        ProvinceBox = new javax.swing.JComboBox();
        //String province[] = {"Ha Noi", "Vinh Phuc"};
        DistrictBox = new javax.swing.JComboBox();
        //String province[] = {"Ha Noi", "Vinh Phuc"};
        WardBox = new javax.swing.JComboBox();
        adressLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        DeleteBtn3 = new javax.swing.JButton();
        ChoosedListLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        servicesList = new JList<>();
        bankLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CurrentServiceList = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Worker Service");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        searchWorkerLabel.setBackground(new java.awt.Color(0, 102, 102));
        searchWorkerLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        searchWorkerLabel.setText("Search Worker");

        nameBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameBtn.setText("Name");

        ProvinceBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ha Noi", "Vinh Phuc"}));
        ProvinceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProvinceBoxActionPerformed(evt);
            }
        });

        DistrictBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ha Noi", "Vinh Phuc"}));

        WardBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ha Noi", "Vinh Phuc"}));

        adressLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adressLabel.setText("Address: (Province, District, Ward)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchWorkerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(nameBtn)
                        .addGap(32, 32, 32)
                        .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DistrictBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProvinceBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WardBox, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(adressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchWorkerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(adressLabel)
                .addGap(22, 22, 22)
                .addComponent(ProvinceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DistrictBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(WardBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CCCD1 - UserID1", "CCCD2 - UserID2", "CCCD3 - UserID3", "CCCD4 - UserID4", "CCCDx - UserIDx","CCCDx - UserIDx","CCCDx - UserIDx","CCCDx - UserIDx","CCCDx - UserIDx" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4);

        DeleteBtn3.setBackground(new java.awt.Color(0, 102, 102));
        DeleteBtn3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DeleteBtn3.setForeground(new java.awt.Color(255, 255, 0));
        DeleteBtn3.setText("Update");
        DeleteBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtn3ActionPerformed(evt);
            }
        });

        ChoosedListLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ChoosedListLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ChoosedListLabel.setText("Current Service List:");

        servicesList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        servicesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Water Facility", "Electronics Facility", "Electronics Devices", "Physical Devices" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        servicesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                servicesListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(servicesList);

        bankLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bankLabel1.setText("Type of services:");

        CurrentServiceList.setColumns(20);
        CurrentServiceList.setRows(5);
        jScrollPane1.setViewportView(CurrentServiceList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChoosedListLabel)
                    .addComponent(bankLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(DeleteBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bankLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChoosedListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProvinceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProvinceBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProvinceBoxActionPerformed
    private void displaySelectedServices() {
        String selectedService = servicesList.getSelectedValue();
        if (ChoosedList.contains(selectedService)) {
            ChoosedList.remove(selectedService);
        } else {
            ChoosedList.add(selectedService);
        }
        String FinalService = "";
        for (String service : ChoosedList) {
            FinalService += service + " ";
        }
        CurrentServiceList.setText("Choosed service: " + FinalService);
    }
    private void servicesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_servicesListValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {
            displaySelectedServices();
        }
    }//GEN-LAST:event_servicesListValueChanged

    private void DeleteBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBtn3ActionPerformed

    private List<String> ChoosedList = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChoosedListLabel;
    private javax.swing.JTextArea CurrentServiceList;
    private javax.swing.JButton DeleteBtn3;
    private javax.swing.JComboBox<String> DistrictBox;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JComboBox<String> ProvinceBox;
    private javax.swing.JComboBox<String> WardBox;
    private javax.swing.JLabel adressLabel;
    private javax.swing.JLabel bankLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel nameBtn;
    private javax.swing.JLabel searchWorkerLabel;
    private javax.swing.JList<String> servicesList;
    // End of variables declaration//GEN-END:variables
}
