/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.easyfixing.mainFunctionalities.PersonalInformation;

import com.mycompany.easyfixing.*;
import com.mycompany.easyfixing.mainFunctionalities.database;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hieut
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPassword
     *
     * @param UserId
     */
    public ChangePassword(int userid ) {
        initComponents();
        UserId = userid;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        newPwd = new javax.swing.JLabel();
        UserInputNewPwd = new javax.swing.JTextField();
        changePwdBtn = new javax.swing.JButton();
        CfnewPassword = new javax.swing.JLabel();
        UserInputNewPassCf = new javax.swing.JTextField();
        currentPwd = new javax.swing.JLabel();
        UserInputCurrentPwd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 102, 102));
        Title.setText("Change Password");

        newPwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newPwd.setText("New Password");

        UserInputNewPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserInputNewPwdActionPerformed(evt);
            }
        });

        changePwdBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        changePwdBtn.setForeground(new java.awt.Color(255, 51, 51));
        changePwdBtn.setText("Update");
        changePwdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePwdBtnActionPerformed(evt);
            }
        });

        CfnewPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CfnewPassword.setText("Confirm new password");

        UserInputNewPassCf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserInputNewPassCfActionPerformed(evt);
            }
        });

        currentPwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        currentPwd.setText("Current Password");

        UserInputCurrentPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserInputCurrentPwdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(Title)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(currentPwd)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(newPwd)
                        .addContainerGap(592, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UserInputNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(changePwdBtn)
                                        .addGap(38, 38, 38))
                                    .addComponent(UserInputCurrentPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CfnewPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UserInputNewPassCf, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentPwd)
                    .addComponent(UserInputCurrentPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPwd)
                    .addComponent(UserInputNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CfnewPassword)
                    .addComponent(UserInputNewPassCf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(changePwdBtn)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserInputNewPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserInputNewPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserInputNewPwdActionPerformed

    private void changePwdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePwdBtnActionPerformed

        // TODO: check if user current pwd input is similar to saved pwd and new pwd is similar to repeat new pwd
        database db = new database();

    }//GEN-LAST:event_changePwdBtnActionPerformed

    private void UserInputNewPassCfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserInputNewPassCfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserInputNewPassCfActionPerformed

    private void UserInputCurrentPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserInputCurrentPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserInputCurrentPwdActionPerformed
    
    public int UserId;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CfnewPassword;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField UserInputCurrentPwd;
    private javax.swing.JTextField UserInputNewPassCf;
    private javax.swing.JTextField UserInputNewPwd;
    private javax.swing.JButton changePwdBtn;
    private javax.swing.JLabel currentPwd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel newPwd;
    // End of variables declaration//GEN-END:variables
}
