/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.easyfixing.mainFunctionalities.PersonalInformation;

import com.mycompany.easyfixing.mainFunctionalities.adminMainActivity;

/**
 *
 * @author hieut
 */
public class UserManageAccount extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public UserManageAccount(int userid) {
        initComponents();
        UserId = userid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        authenBtn = new javax.swing.JButton();
        authenBtn1 = new javax.swing.JButton();
        authenBtn2 = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        authenBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        authenBtn.setForeground(new java.awt.Color(255, 51, 51));
        authenBtn.setText("Change Password");
        authenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authenBtnActionPerformed(evt);
            }
        });

        authenBtn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        authenBtn1.setForeground(new java.awt.Color(255, 51, 51));
        authenBtn1.setText("Delete Account");
        authenBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authenBtn1ActionPerformed(evt);
            }
        });

        authenBtn2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        authenBtn2.setForeground(new java.awt.Color(255, 51, 51));
        authenBtn2.setText("Update Information");
        authenBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authenBtn2ActionPerformed(evt);
            }
        });

        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(authenBtn2)
                            .addComponent(authenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(authenBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(authenBtn2)
                .addGap(53, 53, 53)
                .addComponent(authenBtn)
                .addGap(39, 39, 39)
                .addComponent(authenBtn1)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void authenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authenBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authenBtnActionPerformed

    private void authenBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authenBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authenBtn1ActionPerformed

    private void authenBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authenBtn2ActionPerformed
        // TODO add your handling code here:
        UserPersonalInformation UserPersonalInformationFrame = new UserPersonalInformation(UserId);
        UserPersonalInformationFrame.setVisible(true);
        UserPersonalInformationFrame.pack(); //cause Window be sized to fix layout size
        UserPersonalInformationFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_authenBtn2ActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        adminMainActivity adminMainActivityFrame = new adminMainActivity(UserId);
        adminMainActivityFrame.setVisible(true);
        adminMainActivityFrame.pack(); //cause Window be sized to fix layout size
        adminMainActivityFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_BackButtonActionPerformed

    public javax.swing.JButton getBackBtn() {
        return this.BackButton;
    }

    public javax.swing.JPanel getPanel() {
        return this.jPanel1;
    }
    public int UserId;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton authenBtn;
    private javax.swing.JButton authenBtn1;
    private javax.swing.JButton authenBtn2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
