/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import dashboard.ModelMenu;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author delini
 */
public class MenuItemPanel extends javax.swing.JPanel {

    /**
     * @return the menuSize
     */
    public int getMenuSize() {
        return menuSize;
    }

    /**
     * @param menuSize the menuSize to set
     */
    public void setMenuSize(int menuSize) {
        this.menuSize = menuSize;
    }

    /**
     * @return the titleSize
     */
    public int getTitleSize() {
        return titleSize;
    }

    /**
     * @param titleSize the titleSize to set
     */
    public void setTitleSize(int titleSize) {
        this.titleSize = titleSize;
    }

    /**
     * @return the radius
     */
    public int getRadius() {
        return radius;
    }

    /**
     * @param radius the radius to set
     */
    public void setRadius(int radius) {
        this.radius = radius;
    }

    /**
     * @return the selected
     */
    public boolean isSelected() {
        return selected;
    }

    /**
     * @param selected the selected to set
     */
    public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    }

    private boolean selected;
    private int radius = 5;
    private int menuSize = 20;
    private int titleSize = 22;
    private boolean over;

    /**
     * Creates new form MenuItemPanel
     */
    public MenuItemPanel(ModelMenu data) {
        initComponents();
        setOpaque(false);
        if (null == data.getType()) {
            labelName.setText(" ");
        } else {
            switch (data.getType()) {
                case MENU:
                    labelIcon.setIcon(data.getIcon());
                    labelName.setText(data.getName());
                    labelName.setFont(new Font("Liberation Sans", 0, getMenuSize()));
                    break;
                case TITLE:
                    labelIcon.setText(data.getName());
                    labelIcon.setFont(new Font("Liberation Sans", 1, getTitleSize()));
                    labelName.setVisible(false);
                    break;
                default:
                    labelName.setText(" ");
                    Dimension preferredSize = new Dimension(this.getPreferredSize().width, 20);
                    this.setPreferredSize(preferredSize);
                    break;
            }
        }
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        if (selected || over) {
            Graphics2D g2 = (Graphics2D) grphcs;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            if (selected) {
                g2.setColor(new Color(255, 255, 255, 80));
            } else {
                g2.setColor(new Color(255, 255, 255, 20));
            }
            g2.fillRoundRect(10, 0, getWidth() - 20, getHeight(), getRadius(), getRadius());
        }
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIcon = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();

        labelIcon.setForeground(new java.awt.Color(255, 255, 255));

        labelName.setForeground(new java.awt.Color(255, 255, 255));
        labelName.setText("Menu Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelIcon)
                .addGap(18, 18, 18)
                .addComponent(labelName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelIcon;
    private javax.swing.JLabel labelName;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the over
     */
    public boolean isOver() {
        return over;
    }

    /**
     * @param over the over to set
     */
    public void setOver(boolean over) {
        this.over = over;
        repaint();
    }
}
