/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package adminUserManagement;

import accountManagement.*;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author hieut
 */
public class UserManagement extends javax.swing.JPanel {

    /**
     * Creates new form UserManagement
     */
    public UserManagement() {
        initComponents();
//        setUserID(userid);
    }

    public void addEventDeleteUser(ActionListener event) {
        btnDel.addActionListener(event);
    }
    
    public void addEventAddUser(ActionListener event) {
        btnAdd.addActionListener(event);
    }
    public void addEventUpdateUser(ActionListener event) {
        btnUpdate.addActionListener(event);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDel = new swing.NPLinkButton();
        btnUpdate = new swing.NPLinkButton();
        btnAdd = new swing.NPLinkButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1115, 841));

        btnDel.setText("Delete User");
        btnDel.setBorderColor(new java.awt.Color(247, 205, 139));
        btnDel.setColor(new java.awt.Color(250, 229, 199));
        btnDel.setColorClick(new java.awt.Color(250, 229, 199));
        btnDel.setColorOver(new java.awt.Color(247, 205, 139));
        btnDel.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        btnDel.setRadius(37);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update Worker");
        btnUpdate.setBorderColor(new java.awt.Color(247, 205, 139));
        btnUpdate.setColor(new java.awt.Color(250, 229, 199));
        btnUpdate.setColorClick(new java.awt.Color(250, 229, 199));
        btnUpdate.setColorOver(new java.awt.Color(247, 205, 139));
        btnUpdate.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        btnUpdate.setRadius(37);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setText("Add Worker");
        btnAdd.setBorderColor(new java.awt.Color(247, 205, 139));
        btnAdd.setColor(new java.awt.Color(250, 229, 199));
        btnAdd.setColorClick(new java.awt.Color(250, 229, 199));
        btnAdd.setColorOver(new java.awt.Color(247, 205, 139));
        btnAdd.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        btnAdd.setRadius(37);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
                .addGap(317, 317, 317))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String showDeleteDialog(String message) {
        JTextField textField = new JTextField();
        Object[] messageArray = {message, textField};

        int option = JOptionPane.showConfirmDialog(
                null,
                messageArray,
                "Delete User Account",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (option == JOptionPane.OK_OPTION) {
            return textField.getText();
        } else {
            return "";  // User canceled the input
        }
    }
    public String showGetWorkerIDDialog(String message) {
        JTextField textField = new JTextField();
        Object[] messageArray = {message, textField};

        int option = JOptionPane.showConfirmDialog(
                null,
                messageArray,
                "Update Worker",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (option == JOptionPane.OK_OPTION) {
            return textField.getText();
        } else {
            return "";  // User canceled the input
        }
    }
    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

    }//GEN-LAST:event_btnAddActionPerformed

//    public int getUserID() {
//        return this.UserID;
//    }

//    public void setUserID(int userid) {
//        this.UserID = userid;
//    }

//    private int UserID;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.NPLinkButton btnAdd;
    private swing.NPLinkButton btnDel;
    private swing.NPLinkButton btnUpdate;
    // End of variables declaration//GEN-END:variables
}
