/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.easyfixing;

import javax.swing.JOptionPane;

/**
 *
 * @author hieut
 */
public class ForgetPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPassword
     *
     * @param usermail
     * @param randomkey
     */
    public ForgetPassword(String usermail, int randomkey) {
        initComponents();
        randomKey = randomkey;
        UserMail = usermail;
        receiveEmail.setText("Send authentication code to email: " + usermail);
    }

    private boolean isAuthenticate() {
        if (UserInputAuthenCode.getText() == null ? Integer.toString(randomKey) == null : UserInputAuthenCode.getText().equals(Integer.toString(randomKey))) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        receiveEmail = new javax.swing.JLabel();
        AuthenCode = new javax.swing.JLabel();
        UserInputAuthenCode = new javax.swing.JTextField();
        authenBtn = new javax.swing.JButton();
        comeBackLogin = new javax.swing.JButton();
        newPassword = new javax.swing.JLabel();
        UserInputNewPass = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 102, 102));
        Title.setText("Forget Password");

        receiveEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        receiveEmail.setText("Send authentication code to email:");

        AuthenCode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AuthenCode.setText("Authentication code");

        UserInputAuthenCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserInputAuthenCodeActionPerformed(evt);
            }
        });

        authenBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        authenBtn.setForeground(new java.awt.Color(255, 51, 51));
        authenBtn.setText("Authenticate");
        authenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authenBtnActionPerformed(evt);
            }
        });

        comeBackLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        comeBackLogin.setForeground(new java.awt.Color(255, 51, 51));
        comeBackLogin.setText("Come Back Login");
        comeBackLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comeBackLoginActionPerformed(evt);
            }
        });

        newPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newPassword.setText("New password");

        UserInputNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserInputNewPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(Title)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(receiveEmail)
                            .addComponent(AuthenCode))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comeBackLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UserInputAuthenCode, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(authenBtn)
                                        .addGap(38, 38, 38))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(newPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UserInputNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(receiveEmail)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AuthenCode)
                    .addComponent(UserInputAuthenCode, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPassword)
                    .addComponent(UserInputNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authenBtn)
                    .addComponent(comeBackLogin))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserInputAuthenCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserInputAuthenCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserInputAuthenCodeActionPerformed

    private void authenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authenBtnActionPerformed
        // TODO add your handling code here:
        // check if user authen input is similar to authentication code
        if (isAuthenticate()) {
            //TODO: change interface
            ResetPassword ResetPasswordFrame = new ResetPassword(UserMail);
            ResetPasswordFrame.setVisible(true);
            ResetPasswordFrame.pack(); //cause Window be sized to fix layout size
            ResetPasswordFrame.setLocationRelativeTo(null);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Incorrect authentication code. Please try again!");
        }
        //come back to login
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack(); //cause Window be sized to fix layout size
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_authenBtnActionPerformed

    private void comeBackLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comeBackLoginActionPerformed
        // TODO add your handling code here:
        // come back to Login interface
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack(); //cause Window be sized to fix layout size
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_comeBackLoginActionPerformed

    private void UserInputNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserInputNewPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserInputNewPassActionPerformed

    private String UserMail;
    private final int randomKey;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthenCode;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField UserInputAuthenCode;
    private javax.swing.JTextField UserInputNewPass;
    private javax.swing.JButton authenBtn;
    private javax.swing.JButton comeBackLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel newPassword;
    private javax.swing.JLabel receiveEmail;
    // End of variables declaration//GEN-END:variables
}
