/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.easyfixing;

import java.util.Random;
import javax.swing.JOptionPane;
import com.mycompany.easyfixing.mainFunctionalities.adminMainActivity;
import com.mycompany.easyfixing.mainFunctionalities.customerMainActivity;
import com.mycompany.easyfixing.mainFunctionalities.database;
import com.mycompany.easyfixing.mainFunctionalities.workerMainActivity;
import java.awt.Color;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author hieut
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UserInputEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");

        jPanel1.setToolTipText("");
        jPanel1.setEnabled(false);
        jPanel1.setName(""); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 120, 120));
        jLabel1.setText("LOGIN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Email");

        UserInputEmail.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        UserInputEmail.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                UserInputEmailComponentMoved(evt);
            }
        });
        UserInputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserInputEmailActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Not have existed account?");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(0, 120, 120));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("LOGIN");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton3.setText("Forget password?");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Please fill Email!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(UserInputEmail)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                                .addComponent(loginBtn)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton1))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserInputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ImageIcon getScaledIcon(ImageIcon originalIcon, int desiredWidth, int desiredHeight) {
        // Get the original image from the icon
        Image originalImage = originalIcon.getImage();

        // Create a scaled version of the image
        Image scaledImage = originalImage.getScaledInstance(desiredWidth, desiredHeight, Image.SCALE_SMOOTH);

        // Create a new ImageIcon from the scaled image
        return new ImageIcon(scaledImage);
    }

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        /*
        Deal for check null username or null password
        Deal for getting information from datase: username, password
            +) if account exists, get UserID and UserRole
            +) if account doesn't exist, annouce login fail and prompt user to relogin
        Deal for get authentication if this is a legal account
        Change interface with userRole and save userID for later use
         */

        ImageIcon noNotificationIcon = new ImageIcon("C:\\Users\\hieut\\Documents\\NetBeansProjects\\EasyFixing\\src\\main\\java\\com\\mycompany\\easyfixing\\mainFunctionalities\\icon\\bell.png");
        // Specify the desired size for the image
        int desiredWidth = 50;
        int desiredHeight = 50;
        ImageIcon noNotiIcon = getScaledIcon(noNotificationIcon, desiredWidth, desiredHeight);

        ImageIcon avaIcon = new ImageIcon("C:\\Users\\hieut\\Documents\\NetBeansProjects\\EasyFixing\\src\\main\\java\\com\\mycompany\\easyfixing\\mainFunctionalities\\icon\\anonymousAva.jpg");
        ImageIcon ava = getScaledIcon(avaIcon, 275, 275);

        /*
        Check username and password valid
        if valid, get information from database
         */
        if ((!"".equals(UserInputEmail.getText())) && (!"".equals(jPasswordField1.getText()))) {
            database databaseConnector = new database();
            try {
                boolean checkValid = databaseConnector.checkEmailExistence(UserInputEmail.getText());
                if (checkValid) {
                    int userID = databaseConnector.loginUser(UserInputEmail.getText(), jPasswordField1.getPassword().toString());
                    if (userID > -1) {
                        String userID_string = String.valueOf(userID);
                        // query with id
                        if (databaseConnector.getUserRole(userID_string) == 0) // if role == admin, return admin GUI
                        {
                            /*
        =============== if admin ================
                             */
                            adminMainActivity adminMainActivityFrame = new adminMainActivity();
                            adminMainActivityFrame.setVisible(true);
                            adminMainActivityFrame.pack(); //cause Window be sized to fix layout size
                            adminMainActivityFrame.setLocationRelativeTo(null);

                            //set avatar and information management
                            Color transparentAvaColor = adminMainActivityFrame.getAvaJPanel().getBackground();
                            adminMainActivityFrame.getAvaBtn().setBackground(transparentAvaColor);
                            adminMainActivityFrame.getAvaBtn().setIcon(ava);

                            // if no notice
                            Color transparentColor = adminMainActivityFrame.getBackground();
                            adminMainActivityFrame.getNoticeBtn().setBackground(transparentColor);
                            adminMainActivityFrame.getNoticeBtn().setIcon(noNotiIcon);
                            // if notice
                            // adminMainActivityFrame.notificationBellBtn.setIcon(noticeIcon);
                            this.dispose();
                            // end admin
//        
                        } else if (databaseConnector.getUserRole(userID_string) == 1) {
                            /*
        =============== if customer ================
                             */
                            customerMainActivity customerMainActivityFrame = new customerMainActivity();
                            customerMainActivityFrame.setVisible(true);
                            customerMainActivityFrame.pack(); //cause Window be sized to fix layout size
                            customerMainActivityFrame.setLocationRelativeTo(null);

                            // if no notice
                            Color transparentColor = customerMainActivityFrame.getBackground();
                            customerMainActivityFrame.getNoticeBtn().setBackground(transparentColor);
                            customerMainActivityFrame.getNoticeBtn().setIcon(noNotiIcon);
                            // if notice
                            // customerMainActivityFrame.notificationBellBtn.setIcon(noticeIcon);
                            this.dispose();
                            // end customer
                        } else {
                            /*
        =============== if worker ================
                             */
                            workerMainActivity workerMainActivityFrame = new workerMainActivity();
                            workerMainActivityFrame.setVisible(true);
                            workerMainActivityFrame.pack(); //cause Window be sized to fix layout size
                            workerMainActivityFrame.setLocationRelativeTo(null);

                            // if no notice
                            Color transparentColor = workerMainActivityFrame.getBackground();
                            workerMainActivityFrame.getNoticeBtn().setBackground(transparentColor);
                            workerMainActivityFrame.getNoticeBtn().setIcon(noNotiIcon);
                            // if notice
                            // adminMainActivityFrame.notificationBellBtn.setIcon(noticeIcon);
                            this.dispose();
//         end worker
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "No account exist!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No account exist!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill your information!");
        }


    }//GEN-LAST:event_loginBtnActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // move to sign up interface
        SignUp SignupFrame = new SignUp();
        SignupFrame.setVisible(true);
        SignupFrame.pack(); //cause Window be sized to fix layout size
        SignupFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UserInputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserInputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserInputEmailActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        /*
        Deal for forgeting password:
        +) Check if UserInputEmail filled
        +) Set up for sending email:
           -) generate randomkey for email authentication (4 digits)
           -) get email receiver
           -) get sender information
        +) Send email with 4-digit authentication to receiver
        +) Change interface to SignUpAuthentication
         */
        database db = new database();
        if (!"".equals(UserInputEmail.getText())) {
            try {
                if (db.checkEmailExistence(UserInputEmail.getText())) {
                    Random random = new Random();
                    int randomKey = random.nextInt(9000) + 1000;
                    // receiver
                    final String receiverUsername = UserInputEmail.getText();
                    // sender
                    final String senderUsername = "easyfixinghome@gmail.com";
                    final String senderPassword = "kyhf bugp qede hvoh";
                    // sending email
                    SendAuthenticationEmail sendEmail = new SendAuthenticationEmail(senderUsername, senderPassword, receiverUsername, randomKey);
                    sendEmail.SendEmail();
                    // change to ForgetPassword interface
                    ForgetPassword ForgetPasswordFrame = new ForgetPassword(UserInputEmail.getText(), randomKey);
                    ForgetPasswordFrame.setVisible(true);
                    ForgetPasswordFrame.pack(); //cause Window be sized to fix layout size
                    ForgetPasswordFrame.setLocationRelativeTo(null);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Your email is not exist!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill your email!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void UserInputEmailComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_UserInputEmailComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_UserInputEmailComponentMoved

//    public com.mycompany.easyfixing.mainFunctionalities.database Db;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UserInputEmail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton loginBtn;
    // End of variables declaration//GEN-END:variables

//    void setLocationRelativeTo() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }
}
