/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.easyfixing;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author hieut
 */
public class SignUpAuthentication extends javax.swing.JFrame {

    /**
     * Creates new form SignUpAuthentication
     *
     * @param receiverEmail
     * @param randomKeyFromSignUp
     */
    public SignUpAuthentication(String receiverEmail, int randomKeyFromSignUp) {
        this.counterValue = 60;
        initComponents();
        receiveEmail.setText("Send authentication code to email: " + receiverEmail);
        startCounter();
        randomKey = randomKeyFromSignUp;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receiverEmail = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        receiveEmail = new javax.swing.JLabel();
        AuthenCode = new javax.swing.JLabel();
        UserInputAuthenCode = new javax.swing.JTextField();
        authenBtn = new javax.swing.JButton();
        minCounter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("FILL AUTHENTICATION CODE");

        receiveEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        receiveEmail.setText("Just to hae");

        AuthenCode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AuthenCode.setText("Authentication code");

        UserInputAuthenCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserInputAuthenCodeActionPerformed(evt);
            }
        });

        authenBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        authenBtn.setForeground(new java.awt.Color(255, 51, 51));
        authenBtn.setText("Authenticate");
        authenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authenBtnActionPerformed(evt);
            }
        });

        minCounter.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        minCounter.setForeground(new java.awt.Color(255, 0, 0));
        minCounter.setText("Time Left:");

        javax.swing.GroupLayout receiverEmailLayout = new javax.swing.GroupLayout(receiverEmail);
        receiverEmail.setLayout(receiverEmailLayout);
        receiverEmailLayout.setHorizontalGroup(
            receiverEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiverEmailLayout.createSequentialGroup()
                .addGroup(receiverEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(receiverEmailLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(receiverEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(receiveEmail)
                            .addGroup(receiverEmailLayout.createSequentialGroup()
                                .addComponent(AuthenCode, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(UserInputAuthenCode, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(receiverEmailLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(receiverEmailLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(minCounter)))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receiverEmailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(authenBtn)
                .addGap(275, 275, 275))
        );
        receiverEmailLayout.setVerticalGroup(
            receiverEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiverEmailLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(receiveEmail)
                .addGap(37, 37, 37)
                .addGroup(receiverEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AuthenCode)
                    .addComponent(UserInputAuthenCode, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(authenBtn)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(receiverEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(receiverEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean isAuthenticate() {
        if (UserInputAuthenCode.getText() == null ? Integer.toString(randomKey) == null : UserInputAuthenCode.getText().equals(Integer.toString(randomKey))) {
            return true;
        } else {
            return false;
        }
    }

    private void startCounter() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                minCounter.setText("Time left:" +"00:" + counterValue);
//                System.out.printf(Integer.toString(counterValue));
                if (counterValue > 0) {
                    counterValue--;
                    if (stopTimer) {
                        stopCounter(0);
                        ((Timer) (e.getSource())).stop();
                        /*
                        TODO: Update database
                         */
                        //return login interface
                        Login LoginFrame = new Login();
                        LoginFrame.setVisible(true);
                        LoginFrame.pack();
                        LoginFrame.setLocationRelativeTo(null);
                    }
                } else {
                    stopCounter(1);
                    ((Timer) (e.getSource())).stop();
                    SignUp SignupFrame = new SignUp();
                    SignupFrame.setVisible(true);
                    SignupFrame.pack(); //cause Window be sized to fix layout size
                    SignupFrame.setLocationRelativeTo(null);
                }
            }
        });
        timer.start();
    }

    private void stopCounter(int para) {
        if (para == 1) {
            JOptionPane.showMessageDialog(this, "Out of Time. Please register again!");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Successfully register!!");
            this.dispose();
        }
        // Add logic here if needed when stopping the counter
    }

    private void authenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authenBtnActionPerformed
        // TODO add your handling code here:
        // check if user authen input is similar to authentication code
        if (isAuthenticate()) {
            // to stop counter and timer
            stopTimer = true;
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Incorrect authentication code. Please try again!");
        }
    }//GEN-LAST:event_authenBtnActionPerformed

    private void UserInputAuthenCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserInputAuthenCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserInputAuthenCodeActionPerformed

    private boolean stopTimer = false;
    private int counterValue;
    private final int randomKey;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthenCode;
    private javax.swing.JTextField UserInputAuthenCode;
    private javax.swing.JButton authenBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel minCounter;
    private javax.swing.JLabel receiveEmail;
    private javax.swing.JPanel receiverEmail;
    // End of variables declaration//GEN-END:variables
}
