/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package accountManagement;

import java.awt.event.ActionListener;

/**
 *
 * @author hieut
 */
public class AuthenticatePassword extends javax.swing.JPanel {

    /**
     * Creates new form AuthenticatePassword
     */
    public AuthenticatePassword(String pwd) {
        initComponents();
        txtPass.grabFocus();
        referencePass = pwd;
        labelWrongPass.setVisible(false);
    }

    public void setLabelWrongPass(String text, Boolean visible) {
        if (text != null) {
            labelWrongPass.setText(text);
        }
        if (visible != null) {
            labelWrongPass.setVisible(visible);
        }
    }

    public void addEventConfirm(ActionListener event) {
        btnConfirm.addActionListener(event);
    }

    public String getUserPass() {
        return txtPass.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPass = new swing.NPLinkTextField();
        btnConfirm = new swing.NPLinkButton();
        labelWrongPass = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1115, 841));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 65)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Authenticate Password");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setText("Please input your password");

        txtPass.setBorderFocus(new java.awt.Color(232, 158, 39));
        txtPass.setBorderOff(new java.awt.Color(204, 204, 204));
        txtPass.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        btnConfirm.setText("Confirm");
        btnConfirm.setBorderColor(new java.awt.Color(247, 205, 139));
        btnConfirm.setColor(new java.awt.Color(250, 229, 199));
        btnConfirm.setColorClick(new java.awt.Color(250, 229, 199));
        btnConfirm.setColorOver(new java.awt.Color(247, 205, 139));
        btnConfirm.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        btnConfirm.setRadius(37);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        labelWrongPass.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelWrongPass.setForeground(new java.awt.Color(255, 0, 51));
        labelWrongPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelWrongPass, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel3)
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelWrongPass)
                .addGap(32, 32, 32)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
       
    }//GEN-LAST:event_btnConfirmActionPerformed

    public String getReferencePass() {
        return this.referencePass;
    }

    public void setReferencePass(String pwd) {
        this.referencePass = pwd;
    }

    private String referencePass;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.NPLinkButton btnConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelWrongPass;
    private swing.NPLinkTextField txtPass;
    // End of variables declaration//GEN-END:variables
}
