/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.easyfixing.mainFunctionalities;

/**
 *
 * @author hieut
 */
public class customerMainActivity extends javax.swing.JFrame {

    /**
     * Creates new form mainActivity
     */
    public customerMainActivity(int userid) {
        UserId = userid;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adminNameLabel = new javax.swing.JLabel();
        infoManaBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        notificationBellBtn = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        SearchWorkerbtn = new javax.swing.JButton();
        FeedbackBtn = new javax.swing.JButton();
        historyBtn = new javax.swing.JButton();
        FixingRequestbtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 51)));

        adminNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        adminNameLabel.setForeground(new java.awt.Color(255, 0, 0));
        adminNameLabel.setText("Customer");
        adminNameLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        infoManaBtn.setBorder(null);
        infoManaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoManaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminNameLabel)
                .addGap(59, 59, 59))
            .addComponent(infoManaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(infoManaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(adminNameLabel))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        notificationBellBtn.setBorder(null);
        notificationBellBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationBellBtnActionPerformed(evt);
            }
        });

        welcomeLabel.setFont(new java.awt.Font("Goudy Old Style", 2, 48)); // NOI18N
        welcomeLabel.setText("Welcome \"name\"!");

        SearchWorkerbtn.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        SearchWorkerbtn.setText("Search Worker");

        FeedbackBtn.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        FeedbackBtn.setText("Feedback");

        historyBtn.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        historyBtn.setText("History");

        FixingRequestbtn1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        FixingRequestbtn1.setText("Fixing Request");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(historyBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(FeedbackBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(SearchWorkerbtn)
                                .addGap(44, 44, 44))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notificationBellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(129, Short.MAX_VALUE)
                    .addComponent(FixingRequestbtn1)
                    .addGap(43, 43, 43)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notificationBellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(SearchWorkerbtn)
                .addGap(157, 157, 157)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FeedbackBtn)
                    .addComponent(historyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(271, Short.MAX_VALUE)
                    .addComponent(FixingRequestbtn1)
                    .addGap(168, 168, 168)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //
//    private ImageIcon getScaledIcon(ImageIcon originalIcon, int desiredWidth, int desiredHeight) {
//        // Get the original image from the icon
//        Image originalImage = originalIcon.getImage();
//
//        // Create a scaled version of the image
//        Image scaledImage = originalImage.getScaledInstance(desiredWidth, desiredHeight, Image.SCALE_SMOOTH);
//
//        // Create a new ImageIcon from the scaled image
//        return new ImageIcon(scaledImage);
//    }
    //
    private void notificationBellBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationBellBtnActionPerformed
        // TODO add your handling code here:
//        ImageIcon noNotificationIcon = new ImageIcon("C:\\Users\\hieut\\Documents\\NetBeansProjects\\EasyFixing\\src\\main\\java\\com\\mycompany\\easyfixing\\mainFunctionalities\\icon\\bell.png");
//        // Specify the desired size for the image
//        int desiredWidth = 50;
//        int desiredHeight = 50;
//        ImageIcon scaledIcon = getScaledIcon(noNotificationIcon, desiredWidth, desiredHeight);
//        notificationBellBtn.setIcon(scaledIcon);
    }//GEN-LAST:event_notificationBellBtnActionPerformed

    private void infoManaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoManaBtnActionPerformed
        // TODO add your handling code here:
            // TODO add your handling code here:
        
        // TODO: get present information
        
        // change interface to admin personal information update interface
        UserPersonalInformation customerInfoFrame = new UserPersonalInformation(UserId);
        customerInfoFrame.setVisible(true);
        customerInfoFrame.pack(); //cause Window be sized to fix layout size
        customerInfoFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_infoManaBtnActionPerformed
    public javax.swing.JButton getNoticeBtn()
    {
        return this.notificationBellBtn;
    }
    /**
     * @param args the command line arguments
     */

    public int UserId;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FeedbackBtn;
    private javax.swing.JButton FixingRequestbtn1;
    private javax.swing.JButton SearchWorkerbtn;
    private javax.swing.JLabel adminNameLabel;
    private javax.swing.JButton historyBtn;
    private javax.swing.JButton infoManaBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton notificationBellBtn;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
